(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Yyklab, Welcome to Coot version 0.9.8.96")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon yyklab. Welcome to Coot 0.9.8.96")
(set-display-lists-for-maps 0)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/yyklab/Desktop/Lab_Files/Figure_S1/0F.mtz" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "/Users/yyklab/Desktop/Lab_Files/Figure_S1/0F.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 1 "/crystal/Experimental-data-used-in-refinement/F-obs-filtered" "" "/crystal/Original-experimental-data-mapped-to-asu/R-free-flags" 1 0 0 0.00 0.00)
(make-and-draw-map-with-reso-with-refmac-params "/Users/yyklab/Desktop/Lab_Files/Figure_S1/0F.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 1 "/crystal/Experimental-data-used-in-refinement/F-obs-filtered" "" "/crystal/Original-experimental-data-mapped-to-asu/R-free-flags" 1 0 0 0.00 0.00)
(close-molecule 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/yyklab/Desktop/Lab_Files/base_files/0F.pdb_fittedto55all.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/yyklab/Desktop/Lab_Files/Figure_S1/0F_superposed.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(save-previous-map-colour 4)
(get-map-colour 4)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/yyklab/Desktop/Lab_Files/Figure_S1/SuperposeMaps_1/0F.pdb_fittedto55all_superposed.pdb" 1)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(set-contour-level-in-sigma 1.00)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(save-previous-map-colour 6)
(get-map-colour 6)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(set-contour-level-absolute 2.08)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-general-key-press-hook 65406)
(graphics-general-key-press-hook 16785465)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(set-colour-by-molecule 3)
(set-colour-by-chain 3)
(graphics-to-sec-struct-bonds-representation 3)
(graphics-to-ca-representation 3)
(graphics-to-ca-plus-ligands-representation 3)
(graphics-to-ca-plus-ligands-sec-struct-representation 3)
(graphics-to-rainbow-representation 3)
(graphics-to-bonds-no-waters-representation 3)
(graphics-to-b-factor-cas-representation 3)
(graphics-to-b-factor-representation 3)
(graphics-to-occupancy-representation 3)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(set-contour-level-in-sigma 1.00)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
(graphics-molecule-bond-type 2)
(graphics-molecule-bond-type 3)
(graphics-molecule-bond-type 5)
